language: python
python:
  - 3.4
install:
  - pip install tox
script:
  - tox
env:
  - TIMEZONE=Etc/UTC TOXENV=py26
  - TIMEZONE=Etc/UTC TOXENV=py27
  - TIMEZONE=Etc/UTC TOXENV=py32
  - TIMEZONE=Etc/UTC TOXENV=py33
  - TIMEZONE=Etc/UTC TOXENV=py34
  - TIMEZONE=Etc/UTC TOXENV=pypy
  - TIMEZONE=Etc/UTC TOXENV=pypy3
  - TIMEZONE=Etc/UTC TOXENV=coverage
sudo: false
