language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy
  - pypy3
env:
  - TIMEZONE=Etc/UTC
install:
  - pip install nose
  - pip install coverage
  - pip install mock
  - pip install .
script: nosetests -q tests
